# Site settings
title: Suitmedia Engineering Blog
email: contact@suitmedia.com
description: "Suitmedia is an Indonesia-based digital agency, expert in Internet-based technology, web, mobile apps (iOS, Android, BlackBerry) and digital media strategy."
baseurl: ""
url: "http://suitmedia.github.io"
username: suitmedia
timezone: Asia/Jakarta

# Build settings
markdown: kramdown
permalink: pretty
paginate: 8


fb_app_id: 296407107201754

highlighter: pygments
